
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./static:/app/static
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
    depends_on:
      - app

networks:
  app-network:
    driver: bridge