
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
    depends_on:
      - app